// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  Expression = 2,
  Field = 3,
  FieldName = 4,
  Bool = 5,
  Int = 6,
  String = 7,
  Module = 10,
  Array = 13,
  Grouping = 14,
  When = 15,
  Lambda = 16
