// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  Field = 2,
  FieldName = 3,
  True = 4,
  False = 5,
  Int = 6,
  String = 7,
  Module = 10,
  Array = 13,
  Grouping = 14,
  When = 15,
  Lambda = 16
