// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  Field = 2,
  FieldName = 3,
  Bool = 4,
  Int = 5,
  String = 6,
  Module = 9,
  Array = 12,
  Grouping = 13,
  When = 14,
  Lambda = 15
