// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function coreModule() {
  return Belt_MapString.set(undefined, "id", (function ($$arguments) {
                if ($$arguments.length !== 1) {
                  return {
                          TAG: "Error",
                          _0: "id expects a single argument."
                        };
                }
                var arg = $$arguments[0];
                return {
                        TAG: "Ok",
                        _0: arg
                      };
              }));
}

function stdModules() {
  return Belt_MapString.set(undefined, "core", coreModule());
}

export {
  coreModule ,
  stdModules ,
}
/* No side effect */
