// Generated by ReScript, PLEASE EDIT WITH CARE


function element(value) {
  return {
          value: value,
          type: "element"
        };
}

function slot(value) {
  return {
          value: value,
          type: "slot"
        };
}

function literal(value) {
  return {
          value: value,
          type: "literal"
        };
}

function triple(e, r, v) {
  return {
          element: e,
          role: r,
          value: v
        };
}

function network(value) {
  return {
          value: value,
          type: "network"
        };
}

var emptyNetwork = network([]);

export {
  element ,
  slot ,
  literal ,
  triple ,
  network ,
  emptyNetwork ,
}
/* emptyNetwork Not a pure module */
