// Generated by ReScript, PLEASE EDIT WITH CARE


function element(value) {
  return {
          value: value,
          type: "element"
        };
}

var $$Element = {
  element: element
};

function slot(value) {
  return {
          value: value,
          type: "slot"
        };
}

var Slot = {
  slot: slot
};

function literal(value) {
  return {
          value: value,
          type: "literal"
        };
}

var Literal = {
  literal: literal
};

function printElementPattern(value) {
  return value._0.value;
}

var ElementPattern = {
  printElementPattern: printElementPattern
};

function printValue(v) {
  return v._0.value;
}

var Value = {
  printValue: printValue
};

function triple(e, r, v) {
  return {
          element: e,
          role: r,
          value: v
        };
}

function printTriple(value) {
  return value.element._0.value + " " + value.role._0.value + " " + value.value._0.value;
}

var Triple = {
  triple: triple,
  printTriple: printTriple
};

function network(value) {
  return {
          value: value,
          type: "network"
        };
}

var emptyNetwork_value = [];

var emptyNetwork = {
  value: emptyNetwork_value,
  type: "network"
};

var Network = {
  network: network,
  emptyNetwork: emptyNetwork
};

export {
  $$Element ,
  Slot ,
  Literal ,
  ElementPattern ,
  Value ,
  Triple ,
  Network ,
}
/* No side effect */
