// Generated by ReScript, PLEASE EDIT WITH CARE


function call(name, args) {
  return {
          type: "call",
          commandName: name,
          arguments: args
        };
}

export {
  call ,
}
/* No side effect */
