// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";

function call(name, args) {
  return {
          type: "call",
          commandName: name,
          arguments: args
        };
}

function printValue(value) {
  if (typeof value !== "object") {
    return Js_exn.raiseError("C:\\Users\\berry3\\vsCodeProjects\\ligature-components\\packages\\ligature\\src\\Model.res:32:932-937 - Todo");
  }
  switch (value.TAG) {
    case "Network" :
        return Js_exn.raiseError("C:\\Users\\berry3\\vsCodeProjects\\ligature-components\\packages\\ligature\\src\\Model.res:30:879-884 - Todo");
    case "Quote" :
        return Js_exn.raiseError("C:\\Users\\berry3\\vsCodeProjects\\ligature-components\\packages\\ligature\\src\\Model.res:32:932-937 - Todo");
    default:
      return value._0.value;
  }
}

export {
  call ,
  printValue ,
}
/* No side effect */
