// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Ligature from "./Ligature.res.mjs";

function call(name, args) {
  return {
          type: "call",
          commandName: name,
          arguments: args
        };
}

function printValue(value) {
  if (typeof value !== "object") {
    return Js_exn.raiseError("C:\\Users\\berry3\\vsCodeProjects\\ligature-components\\packages\\ligature\\src\\Model.res:39:1171-1176 - Todo");
  }
  switch (value.TAG) {
    case "Network" :
        var result = {
          contents: "{\n"
        };
        value._0.value.forEach(function (triple) {
              result.contents = result.contents + "  " + Ligature.Triple.printTriple(triple) + ",\n";
            });
        result.contents = result.contents + "}";
        return result.contents;
    case "Quote" :
        return Js_exn.raiseError("C:\\Users\\berry3\\vsCodeProjects\\ligature-components\\packages\\ligature\\src\\Model.res:39:1171-1176 - Todo");
    default:
      return value._0.value;
  }
}

export {
  call ,
  printValue ,
}
/* No side effect */
