// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WanderTokenizerJs from "../WanderTokenizer.js";

function reset(prim) {
  WanderTokenizerJs.reset(prim);
}

function next(prim) {
  return WanderTokenizerJs.next();
}

export {
  reset ,
  next ,
}
/* ../WanderTokenizer.js Not a pure module */
