// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__List from "@rescript/core/src/Core__List.res.mjs";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function textAction(textCb) {
  return function (networks, stack) {
    textCb(Core__List.head(stack));
    console.log(Core__List.head(stack));
    return {
            TAG: "Ok",
            _0: [
              networks,
              Core__List.tail(stack)
            ]
          };
  };
}

function tableAction(textCb) {
  return function (networks, stack) {
    textCb(Core__List.head(stack));
    console.log(Core__List.head(stack));
    return {
            TAG: "Ok",
            _0: [
              networks,
              Core__List.tail(stack)
            ]
          };
  };
}

function graphAction(textCb) {
  return function (networks, stack) {
    textCb(Core__List.head(stack));
    console.log(Core__List.head(stack));
    return {
            TAG: "Ok",
            _0: [
              networks,
              Core__List.tail(stack)
            ]
          };
  };
}

function componentActions(textCb, tableCb, graphCb) {
  return Belt_MapString.fromArray([
              [
                "display-text",
                textAction(textCb)
              ],
              [
                "display-table",
                tableAction(tableCb)
              ],
              [
                "display-graph",
                graphAction(graphCb)
              ]
            ]);
}

export {
  textAction ,
  tableAction ,
  graphAction ,
  componentActions ,
}
/* No side effect */
