// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as WanderParser from "../src/WanderParser.res.mjs";

Ava("parse empty string", (function (t) {
        t.is(WanderParser.parse(""), undefined);
      }));

export {
  
}
/*  Not a pure module */
