// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";

Ava("foo", (function (t) {
        t.pass();
      }));

Ava("bar", (function (t) {
        return Promise.resolve("bar").then(function (bar) {
                    t.is(bar, "bar");
                  });
      }));

export {
  
}
/*  Not a pure module */
