// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Wander from "../src/Wander.res.mjs";

Ava("run empty script", (function (t) {
        t.deepEqual(Wander.run("", undefined), {
              TAG: "Ok",
              _0: undefined
            });
      }));

export {
  
}
/*  Not a pure module */
