// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Ligature from "../src/Ligature.res.mjs";
import * as WanderParser from "../src/WanderParser.res.mjs";

Ava("parse empty string", (function (t) {
        t.deepEqual(WanderParser.parse(""), []);
      }));

Ava("parse single call with no args", (function (t) {
        t.deepEqual(WanderParser.parse("test"), [{
                type: "expression",
                variableName: "",
                contents: [{
                    TAG: "Element",
                    _0: Ligature.$$Element.element("test")
                  }]
              }]);
      }));

export {
  
}
/*  Not a pure module */
