// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Wander from "../src/Wander.res.mjs";

Ava("read empty Network", (function (t) {
        t.deepEqual(Wander.readNetwork("{}"), {
              TAG: "Ok",
              _0: []
            });
      }));

export {
  
}
/*  Not a pure module */
