// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Ligature from "../src/Ligature.res.mjs";
import * as WanderParser from "../src/WanderParser.res.mjs";

Ava("parse empty string", (function (t) {
        t.deepEqual(WanderParser.parse(""), []);
      }));

Ava("parse single call with no args", (function (t) {
        t.deepEqual(WanderParser.parse("test"), [{
                type: "call",
                commandName: "test",
                arguments: []
              }]);
      }));

Ava("parse single call with single arg", (function (t) {
        t.deepEqual(WanderParser.parse("test 1"), [{
                type: "call",
                commandName: "test",
                arguments: [{
                    TAG: "Element",
                    _0: Ligature.element("1")
                  }]
              }]);
      }));

Ava("parse single call with multiple args", (function (t) {
        t.deepEqual(WanderParser.parse("test 1 2 3"), [{
                type: "call",
                commandName: "test",
                arguments: [
                  {
                    TAG: "Element",
                    _0: Ligature.element("1")
                  },
                  {
                    TAG: "Element",
                    _0: Ligature.element("2")
                  },
                  {
                    TAG: "Element",
                    _0: Ligature.element("3")
                  }
                ]
              }]);
      }));

Ava("parse single call with variable arg", (function (t) {
        t.deepEqual(WanderParser.parse("test ?var"), [{
                type: "call",
                commandName: "test",
                arguments: [{
                    TAG: "Variable",
                    _0: Ligature.variable("?var")
                  }]
              }]);
      }));

Ava("parse single call with emppy network arg", (function (t) {
        t.deepEqual(WanderParser.parse("test {}"), [{
                type: "call",
                commandName: "test",
                arguments: [{
                    TAG: "Network",
                    _0: Ligature.network([])
                  }]
              }]);
      }));

Ava("parse single call with network arg", (function (t) {
        t.deepEqual(WanderParser.parse("test {a b c}"), [{
                type: "call",
                commandName: "test",
                arguments: [{
                    TAG: "Network",
                    _0: Ligature.network([Ligature.triple({
                                TAG: "Element",
                                _0: Ligature.element("a")
                              }, {
                                TAG: "Element",
                                _0: Ligature.element("b")
                              }, {
                                TAG: "VElement",
                                _0: Ligature.element("c")
                              })])
                  }]
              }]);
      }));

export {
  
}
/*  Not a pure module */
